import pandas as pd
import matplotlib.pyplot as plt

# Load necessary dataframes
df_orders = datasets["olist_orders_dataset"]
df_order_items = datasets["olist_order_items_dataset"]
df_products = datasets["olist_products_dataset"]
df_category_translation = datasets["product_category_name_translation"]

# Merge order items with orders to get delivery dates
df_merged = pd.merge(df_order_items, df_orders, on='order_id', how='left')

# Merge with products to get product category name
df_merged = pd.merge(df_merged, df_products, on='product_id', how='left')

# Merge with category translation to get English category names
df_merged = pd.merge(df_merged, df_category_translation, on='product_category_name', how='left')

# Convert date columns to datetime
df_merged['order_delivered_customer_date'] = pd.to_datetime(df_merged['order_delivered_customer_date'])
df_merged['order_estimated_delivery_date'] = pd.to_datetime(df_merged['order_estimated_delivery_date'])

# Filter out orders that were not delivered or have missing essential information
df_delivered = df_merged.dropna(subset=['order_delivered_customer_date', 'order_estimated_delivery_date', 'product_category_name_english', 'price'])

# Calculate delivery delay in days
df_delivered['delivery_delay_days'] = (df_delivered['order_delivered_customer_date'] - df_delivered['order_estimated_delivery_date']).dt.days

# Filter for positive delays (actual delays only)
df_delayed = df_delivered[df_delivered['delivery_delay_days'] > 0]

# Group by product category to calculate metrics for delayed items
category_delay_revenue = df_delayed.groupby('product_category_name_english').agg(
    average_delay_days=('delivery_delay_days', 'mean'),
    total_revenue_from_delayed_items=('price', 'sum'),
    num_delayed_items=('product_id', 'count')
).reset_index()

# Calculate average price per delayed item within each category
# This represents the average revenue generated by an item that was delayed
category_delay_revenue['avg_price_per_delayed_item'] = category_delay_revenue['total_revenue_from_delayed_items'] / category_delay_revenue['num_delayed_items']

# Calculate the 'delay relative to revenue' metric
# A higher value indicates more average delay for relatively less average revenue per delayed item
# This identifies categories where delays are impactful given the item's value
category_delay_revenue['delay_relative_to_revenue'] = category_delay_revenue['average_delay_days'] / category_delay_revenue['avg_price_per_delayed_item']

# Handle potential infinite values if avg_price_per_delayed_item is zero
category_delay_revenue = category_delay_revenue.replace([float('inf'), -float('inf')], pd.NA).dropna(subset=['delay_relative_to_revenue'])

# Filter out categories with very few delayed items to avoid noise in the analysis
min_delayed_items_threshold = 50
category_delay_revenue_filtered = category_delay_revenue[category_delay_revenue['num_delayed_items'] >= min_delayed_items_threshold]

# Sort to find the categories with the worst delay relative to revenue
worst_categories = category_delay_revenue_filtered.sort_values(by='delay_relative_to_revenue', ascending=False)

# Get the top 10 worst categories for visualization and summary
top_worst = worst_categories.head(10)

plot_called = False
if not top_worst.empty:
    # Visualization: Bar chart for top 10 categories
    plt.figure(figsize=(12, 7))
    # Sort ascending for barh plot to display the largest value at the top
    plot_data = top_worst.set_index('product_category_name_english')['delay_relative_to_revenue']
    plot_data.sort_values(ascending=True).plot(kind='barh', color='salmon')
    plt.title('Top 10 Product Categories with Worst Delay Relative to Revenue')
    plt.xlabel('Ratio: Average Delay (Days) / Average Price (BRL) per Delayed Item')
    plt.ylabel('Product Category (English)')
    plt.grid(axis='x', linestyle='--', alpha=0.6)
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()
    plot_called = True

# Prepare summary and table
if not top_worst.empty:
    summary_worst_category = top_worst.iloc[0]
    summary_text = (f"The product category '{summary_worst_category['product_category_name_english']}' "
                    f"suffers the worst delay relative to revenue, exhibiting an average delay of "
                    f"{summary_worst_category['average_delay_days']:.2f} days for delayed items, "
                    f"which typically generate an average price of {summary_worst_category['avg_price_per_delayed_item']:.2f} BRL. "
                    f"This results in a high delay-to-revenue ratio of {summary_worst_category['delay_relative_to_revenue']:.2f}.")

    table_output = []
    for index, row in top_worst.iterrows():
        table_output.append((row['product_category_name_english'],
                             (f"Avg Delay: {row['average_delay_days']:.2f} days, "
                              f"Avg Price per Delayed Item: {row['avg_price_per_delayed_item']:.2f} BRL, "
                              f"Ratio (Delay/Price): {row['delay_relative_to_revenue']:.2f}")))
else:
    summary_text = "No product categories with sufficient data on delays and revenue could be identified for this analysis."
    table_output = []

RESULT = {
    "summary": summary_text,
    "table": table_output,
    "plot": plot_called
}
print(f"✅ Summary: {RESULT['summary']}")